// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Smart_Binance_Server.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191008154103_AdditionalRowInserted")]
    partial class AdditionalRowInserted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d385637a-f8d2-46b3-a993-e517539e827d"),
                            Age = 24,
                            Name = "David Lagrange"
                        },
                        new
                        {
                            Id = new Guid("ecdd3716-faf1-4926-9d47-a29750739da2"),
                            Age = 24,
                            Name = "Sierra Seal"
                        },
                        new
                        {
                            Id = new Guid("680971b5-43dc-4f53-a3a4-b9479e9a4176"),
                            Age = 5,
                            Name = "Roma Michele"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
