// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Smart_Binance_Server.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191008183222_RevertTestMigration")]
    partial class RevertTestMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64ede92e-b141-4cdb-8649-46dc9b283caa"),
                            Age = 24,
                            Name = "David Lagrange"
                        },
                        new
                        {
                            Id = new Guid("8e394d0c-0977-42d6-9a95-8bb82049d1ab"),
                            Age = 24,
                            Name = "Sierra Seal"
                        },
                        new
                        {
                            Id = new Guid("988b7471-21ff-469e-ba51-29ba514b7242"),
                            Age = 5,
                            Name = "Roma Michele"
                        },
                        new
                        {
                            Id = new Guid("83577070-05a7-444a-8175-6963017d94ee"),
                            Age = 1,
                            Name = "Harper Lagrange"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
